# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'khoatheworld'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
- {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
- {name: 'Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/khoanewin19'}
- {icon: 'facebook', link: 'https://www.facebook.com/khoanguyengss'}
- {icon: 'instagram', link: 'https://instagram.com/khoanewin'}
- {icon: 'envelope', link: 'mailto:tonynguyenkhoa@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
